name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  ubuntu_build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install valgrind
      - name: Make all
        run: DEBUG=0 make
      - name: Run tests
        run: DEBUG=0 make tests
      - name: Run memory checks
        run: DEBUG=0 make memchecks
      - name: Run code coverage
        run: DEBUG=1 make clean coverage
      - uses: codecov/codecov-action@v1


  macos_build:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Make all
        run: DEBUG=0 make
      - name: Run tests
        run: DEBUG=0 make tests

